### PR TITLE
New Value class semantics

### PR DESCRIPTION
**Pull request by wise86-android**
Hi,
I reworked the class Value, for avoid allocate memory for store integer/float values and avoid to read from a pointer when is not necessary..

I write different constructor for avoid to build a Value with a type and then set a different value
and move the class field as private for manage the set/get only via class method.

### CODE REVIEW

**Comment by kimkulling** [comment]
Hi, thanks a lot for the work, but: now you made using a pool allocator impossible. and that was the reason for using the alloc-scheme in the code.

**Comment by wise86-android** [comment]
I made it impossible, with the new Value or removing the node idx?

**Comment by kimkulling** [comment]
The allocating scheme in value will use a direct new now 😁. So when
switching to a different allocator we have to change more code. Of course
it is not impossible, but more work.
Maybe an example would bei useful?

wise86-android <notifications@github.com> schrieb am Sa., 24. Sep. 2016,
20:07:

**Comment by wise86-android** [comment]
So you idea is to keep all the new related by the class Value inside the ValueAllocator class right?

if yes, I broke your idea also with the previous commit :) since I call a new in the setRef method..
(for that method the best solution will be to use the shear_ptr for keep the Reference pointer..)

Did you consider to use the allocator class like the std::vector do?

By the way,  consider to use an union as this implementation, for avoid to allocate memory also for store a native type.. not allocating memory is for secure more efficient of every allocation strategy ;)

**Comment by kimkulling** [comment]
Breaks architecture.

**Pull request closed without merging**
